export const flags = [
  { flag: '🏁', name: 'Chequered Flag'},
  { flag: '🚩', name: 'Triangular Flag'},
  { flag: '🎌', name: 'Crossed Flags'},
  { flag: '🏴', name: 'Black Flag'},
  { flag: '🏳️', name: 'White Flag'},
  { flag: '🏳️‍🌈', name: 'Rainbow Flag'},
  { flag: '🏴‍☠️', name: 'Pirate Flag'},
  { flag: '🇦🇨', name: 'Ascension Island'},
  { flag: '🇦🇩', name: 'Andorra'},
  { flag: '🇦🇪', name: 'United Arab Emirates'},
  { flag: '🇦🇫', name: 'Afghanistan'},
  { flag: '🇦🇬', name: 'Antigua & Barbuda'},
  { flag: '🇦🇮', name: 'Anguilla'},
  { flag: '🇦🇱', name: 'Albania'},
  { flag: '🇦🇲', name: 'Armenia'},
  { flag: '🇦🇴', name: 'Angola'},
  { flag: '🇦🇶', name: 'Antarctica'},
  { flag: '🇦🇷', name: 'Argentina'},
  { flag: '🇦🇸', name: 'American Samoa'},
  { flag: '🇦🇹', name: 'Austria'},
  { flag: '🇦🇺', name: 'Australia'},
  { flag: '🇦🇼', name: 'Aruba'},
  { flag: '🇦🇽', name: 'Åland Islands'},
  { flag: '🇦🇿', name: 'Azerbaijan'},
  { flag: '🇧🇦', name: 'Bosnia & Herzegovina'},
  { flag: '🇧🇧', name: 'Barbados'},
  { flag: '🇧🇩', name: 'Bangladesh'},
  { flag: '🇧🇪', name: 'Belgium'},
  { flag: '🇧🇫', name: 'Burkina Faso'},
  { flag: '🇧🇬', name: 'Bulgaria'},
  { flag: '🇧🇭', name: 'Bahrain'},
  { flag: '🇧🇮', name: 'Burundi'},
  { flag: '🇧🇯', name: 'Benin'},
  { flag: '🇧🇱', name: 'St. Barthélemy'},
  { flag: '🇧🇲', name: 'Bermuda'},
  { flag: '🇧🇳', name: 'Brunei'},
  { flag: '🇧🇴', name: 'Bolivia'},
  { flag: '🇧🇶', name: 'Caribbean Netherlands'},
  { flag: '🇧🇷', name: 'Brazil'},
  { flag: '🇧🇸', name: 'Bahamas'},
  { flag: '🇧🇹', name: 'Bhutan'},
  { flag: '🇧🇻', name: 'Bouvet Island'},
  { flag: '🇧🇼', name: 'Botswana'},
  { flag: '🇧🇾', name: 'Belarus'},
  { flag: '🇧🇿', name: 'Belize'},
  { flag: '🇨🇦', name: 'Canada'},
  { flag: '🇨🇨', name: 'Cocos (Keeling) Islands'},
  { flag: '🇨🇩', name: 'Congo - Kinshasa'},
  { flag: '🇨🇫', name: 'Central African Republic'},
  { flag: '🇨🇬', name: 'Congo - Brazzaville'},
  { flag: '🇨🇭', name: 'Switzerland'},
  { flag: '🇨🇮', name: 'Côte d’Ivoire'},
  { flag: '🇨🇰', name: 'Cook Islands'},
  { flag: '🇨🇱', name: 'Chile'},
  { flag: '🇨🇲', name: 'Cameroon'},
  { flag: '🇨🇳', name: 'China'},
  { flag: '🇨🇴', name: 'Colombia'},
  { flag: '🇨🇵', name: 'Clipperton Island'},
  { flag: '🇨🇷', name: 'Costa Rica'},
  { flag: '🇨🇺', name: 'Cuba'},
  { flag: '🇨🇻', name: 'Cape Verde'},
  { flag: '🇨🇼', name: 'Curaçao'},
  { flag: '🇨🇽', name: 'Christmas Island'},
  { flag: '🇨🇾', name: 'Cyprus'},
  { flag: '🇨🇿', name: 'Czechia'},
  { flag: '🇩🇪', name: 'Germany'},
  { flag: '🇩🇬', name: 'Diego Garcia'},
  { flag: '🇩🇯', name: 'Djibouti'},
  { flag: '🇩🇰', name: 'Denmark'},
  { flag: '🇩🇲', name: 'Dominica'},
  { flag: '🇩🇴', name: 'Dominican Republic'},
  { flag: '🇩🇿', name: 'Algeria'},
  { flag: '🇪🇦', name: 'Ceuta & Melilla'},
  { flag: '🇪🇨', name: 'Ecuador'},
  { flag: '🇪🇪', name: 'Estonia'},
  { flag: '🇪🇬', name: 'Egypt'},
  { flag: '🇪🇭', name: 'Western Sahara'},
  { flag: '🇪🇷', name: 'Eritrea'},
  { flag: '🇪🇸', name: 'Spain'},
  { flag: '🇪🇹', name: 'Ethiopia'},
  { flag: '🇪🇺', name: 'European Union'},
  { flag: '🇫🇮', name: 'Finland'},
  { flag: '🇫🇯', name: 'Fiji'},
  { flag: '🇫🇰', name: 'Falkland Islands'},
  { flag: '🇫🇲', name: 'Micronesia'},
  { flag: '🇫🇴', name: 'Faroe Islands'},
  { flag: '🇫🇷', name: 'France'},
  { flag: '🇬🇦', name: 'Gabon'},
  { flag: '🇬🇧', name: 'United Kingdom'},
  { flag: '🇬🇩', name: 'Grenada'},
  { flag: '🇬🇪', name: 'Georgia'},
  { flag: '🇬🇫', name: 'French Guiana'},
  { flag: '🇬🇬', name: 'Guernsey'},
  { flag: '🇬🇭', name: 'Ghana'},
  { flag: '🇬🇮', name: 'Gibraltar'},
  { flag: '🇬🇱', name: 'Greenland'},
  { flag: '🇬🇲', name: 'Gambia'},
  { flag: '🇬🇳', name: 'Guinea'},
  { flag: '🇬🇵', name: 'Guadeloupe'},
  { flag: '🇬🇶', name: 'Equatorial Guinea'},
  { flag: '🇬🇷', name: 'Greece'},
  { flag: '🇬🇸', name: 'South Georgia & South Sandwich Islands'},
  { flag: '🇬🇹', name: 'Guatemala'},
  { flag: '🇬🇺', name: 'Guam'},
  { flag: '🇬🇼', name: 'Guinea-Bissau'},
  { flag: '🇬🇾', name: 'Guyana'},
  { flag: '🇭🇰', name: 'Hong Kong SAR China'},
  { flag: '🇭🇲', name: 'Heard & McDonald Islands'},
  { flag: '🇭🇳', name: 'Honduras'},
  { flag: '🇭🇷', name: 'Croatia'},
  { flag: '🇭🇹', name: 'Haiti'},
  { flag: '🇭🇺', name: 'Hungary'},
  { flag: '🇮🇨', name: 'Canary Islands'},
  { flag: '🇮🇩', name: 'Indonesia'},
  { flag: '🇮🇪', name: 'Ireland'},
  { flag: '🇮🇱', name: 'Israel'},
  { flag: '🇮🇲', name: 'Isle of Man'},
  { flag: '🇮🇳', name: 'India'},
  { flag: '🇮🇴', name: 'British Indian Ocean Territory'},
  { flag: '🇮🇶', name: 'Iraq'},
  { flag: '🇮🇷', name: 'Iran'},
  { flag: '🇮🇸', name: 'Iceland'},
  { flag: '🇮🇹', name: 'Italy'},
  { flag: '🇯🇪', name: 'Jersey'},
  { flag: '🇯🇲', name: 'Jamaica'},
  { flag: '🇯🇴', name: 'Jordan'},
  { flag: '🇯🇵', name: 'Japan'},
  { flag: '🇰🇪', name: 'Kenya'},
  { flag: '🇰🇬', name: 'Kyrgyzstan'},
  { flag: '🇰🇭', name: 'Cambodia'},
  { flag: '🇰🇮', name: 'Kiribati'},
  { flag: '🇰🇲', name: 'Comoros'},
  { flag: '🇰🇳', name: 'St. Kitts & Nevis'},
  { flag: '🇰🇵', name: 'North Korea'},
  { flag: '🇰🇷', name: 'South Korea'},
  { flag: '🇰🇼', name: 'Kuwait'},
  { flag: '🇰🇾', name: 'Cayman Islands'},
  { flag: '🇰🇿', name: 'Kazakhstan'},
  { flag: '🇱🇦', name: 'Laos'},
  { flag: '🇱🇧', name: 'Lebanon'},
  { flag: '🇱🇨', name: 'St. Lucia'},
  { flag: '🇱🇮', name: 'Liechtenstein'},
  { flag: '🇱🇰', name: 'Sri Lanka'},
  { flag: '🇱🇷', name: 'Liberia'},
  { flag: '🇱🇸', name: 'Lesotho'},
  { flag: '🇱🇹', name: 'Lithuania'},
  { flag: '🇱🇺', name: 'Luxembourg'},
  { flag: '🇱🇻', name: 'Latvia'},
  { flag: '🇱🇾', name: 'Libya'},
  { flag: '🇲🇦', name: 'Morocco'},
  { flag: '🇲🇨', name: 'Monaco'},
  { flag: '🇲🇩', name: 'Moldova'},
  { flag: '🇲🇪', name: 'Montenegro'},
  { flag: '🇲🇫', name: 'St. Martin'},
  { flag: '🇲🇬', name: 'Madagascar'},
  { flag: '🇲🇭', name: 'Marshall Islands'},
  { flag: '🇲🇰', name: 'North Macedonia'},
  { flag: '🇲🇱', name: 'Mali'},
  { flag: '🇲🇲', name: 'Myanmar (Burma)'},
  { flag: '🇲🇳', name: 'Mongolia'},
  { flag: '🇲🇴', name: 'Macao Sar China'},
  { flag: '🇲🇵', name: 'Northern Mariana Islands'},
  { flag: '🇲🇶', name: 'Martinique'},
  { flag: '🇲🇷', name: 'Mauritania'},
  { flag: '🇲🇸', name: 'Montserrat'},
  { flag: '🇲🇹', name: 'Malta'},
  { flag: '🇲🇺', name: 'Mauritius'},
  { flag: '🇲🇻', name: 'Maldives'},
  { flag: '🇲🇼', name: 'Malawi'},
  { flag: '🇲🇽', name: 'Mexico'},
  { flag: '🇲🇾', name: 'Malaysia'},
  { flag: '🇲🇿', name: 'Mozambique'},
  { flag: '🇳🇦', name: 'Namibia'},
  { flag: '🇳🇨', name: 'New Caledonia'},
  { flag: '🇳🇪', name: 'Niger'},
  { flag: '🇳🇫', name: 'Norfolk Island'},
  { flag: '🇳🇬', name: 'Nigeria'},
  { flag: '🇳🇮', name: 'Nicaragua'},
  { flag: '🇳🇱', name: 'Netherlands'},
  { flag: '🇳🇴', name: 'Norway'},
  { flag: '🇳🇵', name: 'Nepal'},
  { flag: '🇳🇷', name: 'Nauru'},
  { flag: '🇳🇺', name: 'Niue'},
  { flag: '🇳🇿', name: 'New Zealand'},
  { flag: '🇴🇲', name: 'Oman'},
  { flag: '🇵🇦', name: 'Panama'},
  { flag: '🇵🇪', name: 'Peru'},
  { flag: '🇵🇫', name: 'French Polynesia'},
  { flag: '🇵🇬', name: 'Papua New Guinea'},
  { flag: '🇵🇭', name: 'Philippines'},
  { flag: '🇵🇰', name: 'Pakistan'},
  { flag: '🇵🇱', name: 'Poland'},
  { flag: '🇵🇲', name: 'St. Pierre & Miquelon'},
  { flag: '🇵🇳', name: 'Pitcairn Islands'},
  { flag: '🇵🇷', name: 'Puerto Rico'},
  { flag: '🇵🇸', name: 'Palestinian Territories'},
  { flag: '🇵🇹', name: 'Portugal'},
  { flag: '🇵🇼', name: 'Palau'},
  { flag: '🇵🇾', name: 'Paraguay'},
  { flag: '🇶🇦', name: 'Qatar'},
  { flag: '🇷🇪', name: 'Réunion'},
  { flag: '🇷🇴', name: 'Romania'},
  { flag: '🇷🇸', name: 'Serbia'},
  { flag: '🇷🇺', name: 'Russia'},
  { flag: '🇷🇼', name: 'Rwanda'},
  { flag: '🇸🇦', name: 'Saudi Arabia'},
  { flag: '🇸🇧', name: 'Solomon Islands'},
  { flag: '🇸🇨', name: 'Seychelles'},
  { flag: '🇸🇩', name: 'Sudan'},
  { flag: '🇸🇪', name: 'Sweden'},
  { flag: '🇸🇬', name: 'Singapore'},
  { flag: '🇸🇭', name: 'St. Helena'},
  { flag: '🇸🇮', name: 'Slovenia'},
  { flag: '🇸🇯', name: 'Svalbard & Jan Mayen'},
  { flag: '🇸🇰', name: 'Slovakia'},
  { flag: '🇸🇱', name: 'Sierra Leone'},
  { flag: '🇸🇲', name: 'San Marino'},
  { flag: '🇸🇳', name: 'Senegal'},
  { flag: '🇸🇴', name: 'Somalia'},
  { flag: '🇸🇷', name: 'Suriname'},
  { flag: '🇸🇸', name: 'South Sudan'},
  { flag: '🇸🇹', name: 'São Tomé & Príncipe'},
  { flag: '🇸🇻', name: 'El Salvador'},
  { flag: '🇸🇽', name: 'Sint Maarten'},
  { flag: '🇸🇾', name: 'Syria'},
  { flag: '🇸🇿', name: 'Eswatini'},
  { flag: '🇹🇦', name: 'Tristan Da Cunha'},
  { flag: '🇹🇨', name: 'Turks & Caicos Islands'},
  { flag: '🇹🇩', name: 'Chad'},
  { flag: '🇹🇫', name: 'French Southern Territories'},
  { flag: '🇹🇬', name: 'Togo'},
  { flag: '🇹🇭', name: 'Thailand'},
  { flag: '🇹🇯', name: 'Tajikistan'},
  { flag: '🇹🇰', name: 'Tokelau'},
  { flag: '🇹🇱', name: 'Timor-Leste'},
  { flag: '🇹🇲', name: 'Turkmenistan'},
  { flag: '🇹🇳', name: 'Tunisia'},
  { flag: '🇹🇴', name: 'Tonga'},
  { flag: '🇹🇷', name: 'Turkey'},
  { flag: '🇹🇹', name: 'Trinidad & Tobago'},
  { flag: '🇹🇻', name: 'Tuvalu'},
  { flag: '🇹🇼', name: 'Taiwan'},
  { flag: '🇹🇿', name: 'Tanzania'},
  { flag: '🇺🇦', name: 'Ukraine'},
  { flag: '🇺🇬', name: 'Uganda'},
  { flag: '🇺🇲', name: 'U.S. Outlying Islands'},
  { flag: '🇺🇳', name: 'United Nations'},
  { flag: '🇺🇸', name: 'United States of America, USA'},
  { flag: '🇺🇾', name: 'Uruguay'},
  { flag: '🇺🇿', name: 'Uzbekistan'},
  { flag: '🇻🇦', name: 'Vatican City'},
  { flag: '🇻🇨', name: 'St. Vincent & Grenadines'},
  { flag: '🇻🇪', name: 'Venezuela'},
  { flag: '🇻🇬', name: 'British Virgin Islands'},
  { flag: '🇻🇮', name: 'U.S. Virgin Islands'},
  { flag: '🇻🇳', name: 'Vietnam'},
  { flag: '🇻🇺', name: 'Vanuatu'},
  { flag: '🇼🇫', name: 'Wallis & Futuna'},
  { flag: '🇼🇸', name: 'Samoa'},
  { flag: '🇽🇰', name: 'Kosovo'},
  { flag: '🇾🇪', name: 'Yemen'},
  { flag: '🇾🇹', name: 'Mayotte'},
  { flag: '🇿🇦', name: 'South Africa'},
  { flag: '🇿🇲', name: 'Zambia'},
  { flag: '🇿🇼', name: 'Zimbabwe'},
  { flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿', name: 'England'},
  { flag: '🏴󠁧󠁢󠁳󠁣󠁴󠁿', name: 'Scotland'},
  { flag: '🏴󠁧󠁢󠁷󠁬󠁳󠁿', name: 'Wales'},
  { flag: '🏴󠁵󠁳󠁴󠁸󠁿', name: 'Flag for Texas (US-TX)'}
]