export const flags = [
  { flag: '🏁', name: 'Chequered Flag'},
  { flag: '🚩', name: 'Triangular Flag'},
  { flag: '🎌', name: 'Crossed Flags'},
  { flag: '🏴', name: 'Black Flag'},
  { flag: '🏳️', name: 'White Flag'},
  { flag: '🏳️‍🌈', name: 'Rainbow Flag'},
  { flag: '🏴‍☠️', name: 'Pirate Flag'},
  { flag: '🇦🇨', name: 'Ascension Island', },
  { flag: '🇦🇩', name: 'Andorra', code: 'ad'},
  { flag: '🇦🇪', name: 'United Arab Emirates', code: 'ae'},
  { flag: '🇦🇫', name: 'Afghanistan', code: 'af'},
  { flag: '🇦🇬', name: 'Antigua & Barbuda', code: 'ag'},
  { flag: '🇦🇮', name: 'Anguilla', code: 'ai'},
  { flag: '🇦🇱', name: 'Albania', code: 'al'},
  { flag: '🇦🇲', name: 'Armenia', code: 'am'},
  { flag: '🇦🇴', name: 'Angola', code: 'ao'},
  { flag: '🇦🇶', name: 'Antarctica', code: 'aq'},
  { flag: '🇦🇷', name: 'Argentina', code: 'ar'},
  { flag: '🇦🇸', name: 'American Samoa', code: 'as'},
  { flag: '🇦🇹', name: 'Austria', code: 'at'},
  { flag: '🇦🇺', name: 'Australia', code: 'au'},
  { flag: '🇦🇼', name: 'Aruba', code: 'aw'},
  { flag: '🇦🇽', name: 'Åland Islands', code: 'ax'},
  { flag: '🇦🇿', name: 'Azerbaijan', code: 'az'},
  { flag: '🇧🇦', name: 'Bosnia & Herzegovina', code: 'ba'},
  { flag: '🇧🇧', name: 'Barbados', code: 'bb'},
  { flag: '🇧🇩', name: 'Bangladesh', code: 'bd'},
  { flag: '🇧🇬', name: 'Bulgaria', code: 'bg'},
  { name: 'Burkina Faso', code: 'bf', flag: '🇧🇫'},
  { flag: '🇧🇭', name: 'Bahrain', code: 'bh'},
  { flag: '🇧🇮', name: 'Burundi', code: 'bi'},
  { flag: '🇧🇯', name: 'Benin', code: 'bj'},
  { flag: '🇧🇱', name: 'St. Barthélemy', code: 'bl'},
  { flag: '🇧🇲', name: 'Bermuda', code: 'bm'},
  { flag: '🇧🇳', name: 'Brunei', code: 'bn'},
  { flag: '🇧🇴', name: 'Bolivia', code: 'bo'},
  { flag: '🇧🇶', name: 'Caribbean Netherlands', code: 'bq'},
  { flag: '🇧🇷', name: 'Brazil', code: 'br'},
  { flag: '🇧🇸', name: 'Bahamas', code: 'bs'},
  { flag: '🇧🇹', name: 'Bhutan', code: 'bt'},
  { flag: '🇧🇻', name: 'Bouvet Island', code: 'bv'},
  { flag: '🇧🇼', name: 'Botswana', code: 'bw'},
  { flag: '🇧🇾', name: 'Belarus', code:'by'},
  { flag: '🇧🇿', name: 'Belize', code: 'bz'},
  { flag: '??', name: 'Belgium', code: 'be'},
  { flag: '🇨🇦', name: 'Canada', code: 'ca'},
  { flag: '🇨🇨', name: 'Cocos (Keeling) Islands', code: 'cc'},
  { flag: '🇨🇩', name: 'Congo - Kinshasa', code: 'cd'},
  { flag: '🇨🇫', name: 'Central African Republic', code: 'cf'},
  { flag: '🇨🇬', name: 'Congo - Brazzaville', code: 'cg'},
  { flag: '🇨🇭', name: 'Switzerland', code: 'ch'},
  { flag: '🇨🇮', name: 'Côte d’Ivoire', code: 'ci'},
  { flag: '🇨🇰', name: 'Cook Islands', code: 'ck'},
  { flag: '🇨🇱', name: 'Chile', code: 'cl'},
  { flag: '🇨🇲', name: 'Cameroon', code: 'cm'},
  { flag: '🇨🇳', name: 'China', code: 'cn'},
  { flag: '🇨🇴', name: 'Colombia', code: 'co'},
  { flag: '🇨🇵', name: 'Clipperton Island', code: 'cp'},
  { flag: '🇨🇷', name: 'Costa Rica', code: 'cr'},
  { flag: '🇨🇺', name: 'Cuba', code: 'cu'},
  { flag: '🇨🇻', name: 'Cape Verde', code: 'cv'},
  { flag: '🇨🇼', name: 'Curaçao', code: 'cw'},
  { flag: '🇨🇽', name: 'Christmas Island', code: 'cx'},
  { flag: '🇨🇾', name: 'Cyprus', code: 'cy'},
  { flag: '🇨🇿', name: 'Czechia', code: 'cz'},
  { flag: '🇩🇪', name: 'Germany', code: 'de'},
  { flag: '🇩🇬', name: 'Diego Garcia', code: 'dg'},
  { flag: '🇩🇯', name: 'Djibouti', code: 'dj'},
  { flag: '🇩🇰', name: 'Denmark', code: 'dk'},
  { flag: '🇩🇲', name: 'Dominica', code: 'dm'},
  { flag: '🇩🇴', name: 'Dominican Republic', code: 'do'},
  { flag: '🇩🇿', name: 'Algeria', code: 'dz'},
  { flag: '🇪🇦', name: 'Ceuta & Melilla', code: 'ea'},
  { flag: '🇪🇨', name: 'Ecuador', code: 'ec'},
  { flag: '🇪🇪', name: 'Estonia', code: 'ee'},
  { flag: '🇪🇬', name: 'Egypt', code: 'eg'},
  { flag: '🇪🇭', name: 'Western Sahara', code: 'eh'},
  { flag: '🇪🇷', name: 'Eritrea', code: 'er'},
  { flag: '🇪🇸', name: 'Spain', code: 'es'},
  { flag: '🇪🇹', name: 'Ethiopia', code: 'et'},
  { flag: '🇪🇺', name: 'European Union', },
  { flag: '🇫🇮', name: 'Finland', code: 'fi'},
  { flag: '🇫🇯', name: 'Fiji', code: 'fj'},
  { flag: '🇫🇰', name: 'Falkland Islands', code: 'fk'},
  { flag: '🇫🇲', name: 'Micronesia', code: 'fm'},
  { flag: '🇫🇴', name: 'Faroe Islands', code: 'fo'},
  { flag: '🇫🇷', name: 'France', code: 'fr'},
  { flag: '🇬🇦', name: 'Gabon', code: 'ga'},
  { flag: '🇬🇧', name: 'United Kingdom', },
  { flag: '🇬🇩', name: 'Grenada', code: 'gd'},
  { flag: '🇬🇪', name: 'Georgia', code: 'ge'},
  { flag: '🇬🇫', name: 'French Guiana', code: 'gf'},
  { flag: '🇬🇬', name: 'Guernsey', code: 'gg'},
  { flag: '🇬🇭', name: 'Ghana', code: 'gh'},
  { flag: '🇬🇮', name: 'Gibraltar', code: 'gi'},
  { flag: '🇬🇱', name: 'Greenland', code: 'gl'},
  { flag: '🇬🇲', name: 'Gambia', code: 'gm'},
  { flag: '🇬🇳', name: 'Guinea', code: 'gn'},
  { flag: '🇬🇵', name: 'Guadeloupe', code: 'gp'},
  { flag: '🇬🇶', name: 'Equatorial Guinea', code: 'gq'},
  { flag: '🇬🇷', name: 'Greece', code: 'gr'},
  { flag: '🇬🇸', name: 'South Georgia & South Sandwich Islands', code: 'gs'},
  { flag: '🇬🇹', name: 'Guatemala', code: 'gt'},
  { flag: '🇬🇺', name: 'Guam', code: 'gu'},
  { flag: '🇬🇼', name: 'Guinea-Bissau', code: 'gw'},
  { flag: '🇬🇾', name: 'Guyana', code: 'gy'},
  { flag: '🇭🇰', name: 'Hong Kong SAR China', code: 'hk'},
  { flag: '🇭🇲', name: 'Heard & McDonald Islands', code: 'hm'},
  { flag: '🇭🇳', name: 'Honduras', code: 'hn'},
  { flag: '🇭🇷', name: 'Croatia', code: 'hr'},
  { flag: '🇭🇹', name: 'Haiti', code: 'ht'},
  { flag: '🇭🇺', name: 'Hungary', code: 'hu'},
  { flag: '🇮🇨', name: 'Canary Islands', code: 'ic'},
  { flag: '🇮🇩', name: 'Indonesia', code: 'id'},
  { flag: '🇮🇪', name: 'Ireland', code: 'ie'},
  { flag: '🇮🇱', name: 'Israel', code: 'il'},
  { flag: '🇮🇲', name: 'Isle of Man'},
  { flag: '🇮🇳', name: 'India', code: 'in'},
  { flag: '🇮🇴', name: 'British Indian Ocean Territory', code: 'io'},
  { flag: '🇮🇶', name: 'Iraq', code: 'iq'},
  { flag: '🇮🇷', name: 'Iran', code: 'ir'},
  { flag: '🇮🇸', name: 'Iceland', code: 'is'},
  { flag: '🇮🇹', name: 'Italy', code: 'it'},
  { flag: '🇯🇪', name: 'Jersey', code: 'je'},
  { flag: '🇯🇲', name: 'Jamaica', code: 'jm'},
  { flag: '🇯🇴', name: 'Jordan', code: 'jo'},
  { flag: '🇯🇵', name: 'Japan', code: 'jp'},
  { flag: '🇰🇪', name: 'Kenya', code: 'ke'},
  { flag: '🇰🇬', name: 'Kyrgyzstan', code: 'kg'},
  { flag: '🇰🇭', name: 'Cambodia', code: 'kh'},
  { flag: '🇰🇮', name: 'Kiribati', code: 'ki'},
  { flag: '🇰🇲', name: 'Comoros', code: 'km'},
  { flag: '🇰🇳', name: 'St. Kitts & Nevis', code: 'kn'},
  { flag: '🇰🇵', name: 'North Korea', code: 'kp'},
  { flag: '🇰🇷', name: 'South Korea', code: 'kr'},
  { flag: '🇰🇼', name: 'Kuwait', code: 'kw'},
  { flag: '🇰🇾', name: 'Cayman Islands', code: 'ky'},
  { flag: '🇰🇿', name: 'Kazakhstan', code: 'kz'},
  { flag: '🇱🇦', name: 'Laos', code: 'la'},
  { flag: '🇱🇧', name: 'Lebanon', code: 'lb'},
  { flag: '🇱🇨', name: 'St. Lucia', code: 'lc'},
  { flag: '🇱🇮', name: 'Liechtenstein', code: 'li'},
  { flag: '🇱🇰', name: 'Sri Lanka', code: 'lk'},
  { flag: '🇱🇷', name: 'Liberia', code: 'lr'},
  { flag: '🇱🇸', name: 'Lesotho', code: 'ls'},
  { flag: '🇱🇹', name: 'Lithuania', code: 'lt'},
  { flag: '🇱🇺', name: 'Luxembourg', code: 'lu'},
  { flag: '🇱🇻', name: 'Latvia', code: 'lv'},
  { flag: '🇱🇾', name: 'Libya', code: 'ly'},
  { flag: '🇲🇦', name: 'Morocco', code: 'ma'},
  { flag: '🇲🇨', name: 'Monaco', code: 'mc'},
  { flag: '🇲🇩', name: 'Moldova', code: 'md'},
  { flag: '🇲🇪', name: 'Montenegro', code: 'me'},
  { flag: '🇲🇫', name: 'St. Martin', code: 'mf'},
  { flag: '🇲🇬', name: 'Madagascar', code: 'mg'},
  { flag: '🇲🇭', name: 'Marshall Islands', code: 'mh'},
  { flag: '🇲🇰', name: 'North Macedonia', code: 'mk'},
  { flag: '🇲🇱', name: 'Mali', code: 'ml'},
  { flag: '🇲🇲', name: 'Myanmar (Burma)', code: 'mm'},
  { flag: '🇲🇳', name: 'Mongolia', code: 'mn'},
  { flag: '🇲🇴', name: 'Macao Sar China', code: 'mo'},
  { flag: '🇲🇵', name: 'Northern Mariana Islands', code: 'mp'},
  { flag: '🇲🇶', name: 'Martinique', code: 'mq'},
  { flag: '🇲🇷', name: 'Mauritania', code: 'mr'},
  { flag: '🇲🇸', name: 'Montserrat', code: 'ms'},
  { flag: '🇲🇹', name: 'Malta', code: 'mt'},
  { flag: '🇲🇺', name: 'Mauritius', code: 'mu'},
  { flag: '🇲🇻', name: 'Maldives', code: 'mv'},
  { flag: '🇲🇼', name: 'Malawi', code: 'mw'},
  { flag: '🇲🇽', name: 'Mexico', code: 'mx'},
  { flag: '🇲🇾', name: 'Malaysia', code: 'my'},
  { flag: '🇲🇿', name: 'Mozambique', code: 'mz'},
  { flag: '🇳🇦', name: 'Namibia', code: 'na'},
  { flag: '🇳🇨', name: 'New Caledonia', code: 'nc'},
  { flag: '🇳🇪', name: 'Niger', code: 'ne'},
  { flag: '🇳🇫', name: 'Norfolk Island', code: 'nf'},
  { flag: '🇳🇬', name: 'Nigeria', code: 'ng'},
  { flag: '🇳🇮', name: 'Nicaragua', code: 'ni'},
  { flag: '🇳🇱', name: 'Netherlands', code: 'nl'},
  { flag: '🇳🇴', name: 'Norway', code: 'no'},
  { flag: '🇳🇵', name: 'Nepal', code: 'np'},
  { flag: '🇳🇷', name: 'Nauru', code: 'nr'},
  { flag: '🇳🇺', name: 'Niue', code: 'nu'},
  { flag: '🇳🇿', name: 'New Zealand', code: 'nz'},
  { flag: '🇴🇲', name: 'Oman', code: 'om'},
  { flag: '🇵🇦', name: 'Panama', code: 'pa'},
  { flag: '🇵🇪', name: 'Peru',   code: 'pe'},
  { flag: '🇵🇫', name: 'French Polynesia', code: 'pf'},
  { flag: '🇵🇬', name: 'Papua New Guinea', code: 'pg'},
  { flag: '🇵🇭', name: 'Philippines', code: 'ph'},
  { flag: '🇵🇰', name: 'Pakistan', code: 'pk'},
  { flag: '🇵🇱', name: 'Poland', code: 'pl'},
  { flag: '🇵🇲', name: 'St. Pierre & Miquelon', code: 'pm'},
  { flag: '🇵🇳', name: 'Pitcairn Islands', code: 'pn'},
  { flag: '🇵🇷', name: 'Puerto Rico', code: 'pr'},
  { flag: '🇵🇸', name: 'Palestinian Territories', code: 'ps'},
  { flag: '🇵🇹', name: 'Portugal', code: 'pt'},
  { flag: '🇵🇼', name: 'Palau', code: 'pw'},
  { flag: '🇵🇾', name: 'Paraguay', code: 'py'},
  { flag: '🇶🇦', name: 'Qatar', code: 'qa'},
  { flag: '🇷🇪', name: 'Réunion', code: 're'},
  { flag: '🇷🇴', name: 'Romania', code: 'ro'},
  { flag: '🇷🇸', name: 'Serbia', code: 'rs'},
  { flag: '🇷🇺', name: 'Russia', code: 'ru'},
  { flag: '🇷🇼', name: 'Rwanda', code: 'rw'},
  { flag: '🇸🇦', name: 'Saudi Arabia', code: 'sa'},
  { flag: '🇸🇧', name: 'Solomon Islands', code: 'sb'},
  { flag: '🇸🇨', name: 'Seychelles', code: 'sc'},
  { flag: '🇸🇩', name: 'Sudan', code: 'sd'},
  { flag: '🇸🇪', name: 'Sweden', code: 'se'},
  { flag: '🇸🇬', name: 'Singapore', code: 'sg'},
  { flag: '🇸🇭', name: 'St. Helena', code: 'sh'},
  { flag: '🇸🇮', name: 'Slovenia', code: 'si'},
  { flag: '🇸🇯', name: 'Svalbard & Jan Mayen', code: 'sj'},
  { flag: '🇸🇰', name: 'Slovakia', code: 'sk'},
  { flag: '🇸🇱', name: 'Sierra Leone', code: 'sl'},
  { flag: '🇸🇲', name: 'San Marino', code: 'sm'},
  { flag: '🇸🇳', name: 'Senegal', code: 'sn'},
  { flag: '🇸🇴', name: 'Somalia', code: 'so'},
  { flag: '🇸🇷', name: 'Suriname', code: 'sr'},
  { flag: '🇸🇸', name: 'South Sudan', code: 'ss'},
  { flag: '🇸🇹', name: 'São Tomé & Príncipe', code: 'st'},
  { flag: '🇸🇻', name: 'El Salvador', code: 'sv'},
  { flag: '🇸🇽', name: 'Sint Maarten', code: 'sx'},
  { flag: '🇸🇾', name: 'Syria', code: 'sy'},
  { flag: '🇸🇯', name: 'Svalbard & Jan Mayen', code: 'sj'},,
  { flag: '🇹🇦', name: 'Tristan Da Cunha', code: 'sx'},
  { flag: '🇹🇨', name: 'Turks & Caicos Islands', code: 'tc'},
  { flag: '🇹🇩', name: 'Chad', code: 'td'},
  { flag: '🇹🇫', name: 'French Southern Territories', code: 'tf'},
  { flag: '🇹🇬', name: 'Togo', code: 'tg'},
  { flag: '🇹🇭', name: 'Thailand', code: 'th'},
  { flag: '🇹🇯', name: 'Tajikistan', code: 'tj'},
  { flag: '🇹🇰', name: 'Tokelau', code: 'tk'},
  { flag: '🇹🇱', name: 'Timor-Leste', code: 'tl'},
  { flag: '🇹🇲', name: 'Turkmenistan', code: 'tm'},
  { flag: '🇹🇳', name: 'Tunisia', code: 'tn'},
  { flag: '🇹🇴', name: 'Tonga', code: 'to'},
  { flag: '🇹🇷', name: 'Turkey', code: 'tr'},
  { flag: '🇹🇹', name: 'Trinidad & Tobago', code: 'tt'},
  { flag: '🇹🇻', name: 'Tuvalu', code: 'tv'},
  { flag: '🇹🇼', name: 'Taiwan', code: 'tw'},
  { flag: '🇹🇿', name: 'Tanzania', code: 'tz'},
  { flag: '🇺🇦', name: 'Ukraine', code: 'ua'},
  { flag: '🇺🇬', name: 'Uganda', code: 'ug'},
  { flag: '🇺🇲', name: 'U.S. Outlying Islands', code: 'um'},
  { flag: '🇺🇳', name: 'United Nations', code: 'un'},
  { flag: '🇺🇸', name: 'United States of America, USA', code: 'us'},
  { flag: '🇺🇾', name: 'Uruguay', code: 'uy'},
  { flag: '🇺🇿', name: 'Uzbekistan', code: 'uz'},
  { flag: '🇻🇦', name: 'Vatican City', code: 'va'},
  { flag: '🇻🇨', name: 'St. Vincent & Grenadines', code: 'vc'},
  { flag: '🇻🇪', name: 'Venezuela', code: 've'},
  { flag: '🇻🇬', name: 'British Virgin Islands', code: 'vg'},
  { flag: '🇻🇮', name: 'U.S. Virgin Islands', code: 'vi'},
  { flag: '🇻🇳', name: 'Vietnam', code: 'vn'},
  { flag: '🇻🇺', name: 'Vanuatu', code: 'vu'},
  { flag: '🇼🇫', name: 'Wallis & Futuna', code: 'wf'},
  { flag: '🇼🇸', name: 'Samoa', code: 'ws'},
  { flag: '🇽🇰', name: 'Kosovo', code: 'xk'},
  { flag: '🇾🇪', name: 'Yemen', code: 'ye'},
  { flag: '🇾🇹', name: 'Mayotte', code: 'yt'},
  { flag: '🇿🇦', name: 'South Africa', code: 'za'},
  { flag: '🇿🇲', name: 'Zambia', code: 'zm'},
  { flag: '🇿🇼', name: 'Zimbabwe', code: 'zw'},
  { flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿', name: 'England', code: 'gb'},
  { flag: '🏴󠁧󠁢󠁳󠁣󠁴󠁿', name: 'Scotland', code: 'gb'},
  { flag: '🏴󠁧󠁢󠁷󠁬󠁳󠁿', name: 'Wales', code: 'gb'},
  { flag: '🏴󠁵󠁳󠁴󠁸󠁿', name: 'Flag for Texas (US-TX)', code: 'us'},
];