import './common/native.shim';
import './button';
import './calendar';
import './carousel';
import './clock';
import './color-picker';
import './common';
import {openDialog} from './dialog';
import './div';
import './flow-controls';
import './http';
import './input';
import './list';
import {XMapbox} from './mapbox';
import './pre';
import './number';
import './overlay';
import './pagination';
import './select';
import {addSnackbar} from './snackbar';
import './i';
import './table';
import './tabs';
import './textfield';
import './tooltip';
import './ul';

window.openDialog = openDialog;
window.addSnackbar = addSnackbar;
export {XMapbox};
